import 'server-only';

import { Category, ImageMetadata, Product } from './mongodb/schema';

type SeedProductData = Omit<Product, 'categoryIds' | 'createdAt' | 'updatedAt'> & {
  categorySlugs: string[];
};

export const seedCategories: Omit<Category, 'createdAt' | 'updatedAt'>[] = [
  { name: 'CPUs', slug: 'cpus', description: 'Central Processing Units.' },
  { name: 'Motherboards', slug: 'motherboards', description: 'Connects components.' },
  { name: 'Memory (RAM)', slug: 'memory-ram', description: 'Temporary storage.' },
  { name: 'Storage', slug: 'storage', description: 'HDDs and SSDs.' },
  { name: 'Video Cards (GPUs)', slug: 'video-cards-gpus', description: 'Graphics processing.' },
  { name: 'Power Supplies (PSUs)', slug: 'power-supplies-psus', description: 'Provides power.' },
  { name: 'PC Cases', slug: 'pc-cases', description: 'PC enclosure.' },
  { name: 'Monitors', slug: 'monitors', description: 'Displays.' },
  { name: 'Keyboards', slug: 'keyboards', description: 'Typing input.' },
  { name: 'Mice', slug: 'mice', description: 'Pointing devices.' },
  { name: 'Headsets & Audio', slug: 'headsets-audio', description: 'Audio devices.' },
  { name: 'Webcams', slug: 'webcams', description: 'Video cameras.' },
  { name: 'Laptops', slug: 'laptops', description: 'Portable computers.' },
  { name: 'Desktops', slug: 'desktops', description: 'Pre-built PCs.' },
  { name: 'Cables & Adapters', slug: 'cables-adapters', description: 'Connectors.' },
  { name: 'Networking', slug: 'networking', description: 'Network gear.' },
  { name: 'Software', slug: 'software', description: 'OS and Apps.' },
  { name: 'PC Cooling', slug: 'pc-cooling', description: 'Cooling solutions.' },
];

const placeholderImg = (text: string, count = 1): ImageMetadata[] =>
  Array.from({ length: count }, (_, i) => ({
    url: `https://placehold.co/400x400.png?text=${encodeURIComponent(text)}${count > 1 ? `+${i + 1}` : ''}`,
    alt: `${text}${count > 1 ? ` - Image ${i + 1}` : ''}`,
  }));

export const seedProducts: SeedProductData[] = [
  // --- CPUs (10+) ---
  {
    name: 'QuantumCore i9-14900K',
    slug: 'quantumcore-i9-14900k',
    description: 'Top-tier unlocked CPU.',
    price: 589.99,
    stock: 70,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU i9 14900K', 2),
  },
  {
    name: 'QuantumCore i7-14700K',
    slug: 'quantumcore-i7-14700k',
    description: 'High-end unlocked CPU.',
    price: 409.0,
    stock: 150,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU i7 14700K'),
  },
  {
    name: 'QuantumCore i5-14600K',
    slug: 'quantumcore-i5-14600k',
    description: 'Mid-range unlocked CPU.',
    price: 319.0,
    stock: 200,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU i5 14600K'),
  },
  {
    name: 'Zenith Ryzen 9 7950X',
    slug: 'zenith-ryzen-9-7950x',
    description: 'Top-tier AMD CPU.',
    price: 549.0,
    stock: 90,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU R9 7950X', 2),
  },
  {
    name: 'Zenith Ryzen 7 7800X3D',
    slug: 'zenith-ryzen-7-7800x3d',
    description: 'Best gaming CPU with 3D V-Cache.',
    price: 399.0,
    stock: 180,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU R7 7800X3D'),
  },
  {
    name: 'Zenith Ryzen 7 7700X',
    slug: 'zenith-ryzen-7-7700x',
    description: 'Excellent AMD CPU for gaming/productivity.',
    price: 349.0,
    stock: 250,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU R7 7700X'),
  },
  {
    name: 'Zenith Ryzen 5 7600X',
    slug: 'zenith-ryzen-5-7600x',
    description: 'Great value AMD CPU.',
    price: 249.0,
    stock: 300,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU R5 7600X'),
  },
  {
    name: 'QuantumCore i3-14100',
    slug: 'quantumcore-i3-14100',
    description: 'Entry-level Intel CPU.',
    price: 139.99,
    stock: 150,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU i3 14100'),
  },
  {
    name: 'Zenith Ryzen 5 5600G',
    slug: 'zenith-ryzen-5-5600g',
    description: 'APU with integrated graphics.',
    price: 129.0,
    stock: 220,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU R5 5600G'),
  },
  {
    name: 'QuantumCore i9-13900KS',
    slug: 'quantumcore-i9-13900ks',
    description: 'Previous gen flagship.',
    price: 549.99,
    stock: 50,
    categorySlugs: ['cpus'],
    images: placeholderImg('CPU i9 13900KS', 2),
  },

  // --- Motherboards (10+) ---
  {
    name: 'AuraSync Z790 MAX',
    slug: 'aurasync-z790-max',
    description: 'High-end Intel Z790 board.',
    price: 499.99,
    stock: 80,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo Z790 Max', 2),
  },
  {
    name: 'GigaByte Z790 AORUS Elite',
    slug: 'gigabyte-z790-aorus-elite',
    description: 'Popular Intel Z790 board.',
    price: 249.99,
    stock: 150,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo Z790 Elite'),
  },
  {
    name: 'MicroATX B760M Pro',
    slug: 'microatx-b760m-pro',
    description: 'Value Intel B760 mATX board.',
    price: 129.99,
    stock: 200,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo B760M Pro'),
  },
  {
    name: 'AuraSync X670E Hero',
    slug: 'aurasync-x670e-hero',
    description: 'High-end AMD X670E board.',
    price: 699.99,
    stock: 60,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo X670E Hero', 2),
  },
  {
    name: 'GigaByte B650 AORUS Pro',
    slug: 'gigabyte-b650-aorus-pro',
    description: 'Feature-rich AMD B650 board.',
    price: 279.99,
    stock: 180,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo B650 Pro'),
  },
  {
    name: 'MicroATX B650M DS3H',
    slug: 'microatx-b650m-ds3h',
    description: 'Budget AMD B650 mATX board.',
    price: 149.99,
    stock: 250,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo B650M DS3H'),
  },
  {
    name: 'MiniITX Z790I Strix',
    slug: 'miniitx-z790i-strix',
    description: 'Compact Intel ITX board.',
    price: 429.99,
    stock: 70,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo Z790I ITX'),
  },
  {
    name: 'MiniITX B650I Edge WiFi',
    slug: 'miniitx-b650i-edge-wifi',
    description: 'Compact AMD ITX board.',
    price: 259.99,
    stock: 110,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo B650I ITX'),
  },
  {
    name: 'ProArt Z790 Creator WiFi',
    slug: 'proart-z790-creator-wifi',
    description: 'Intel board for creators.',
    price: 599.99,
    stock: 55,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo Z790 Creator', 2),
  },
  {
    name: 'ProArt X670E Creator WiFi',
    slug: 'proart-x670e-creator-wifi',
    description: 'AMD board for creators.',
    price: 479.99,
    stock: 65,
    categorySlugs: ['motherboards'],
    images: placeholderImg('Mobo X670E Creator'),
  },

  // --- Memory (RAM) (10+) ---
  {
    name: 'Vengeance DDR5 32GB Kit',
    slug: 'vengeance-ddr5-32gb-kit',
    description: 'Popular DDR5 32GB kit.',
    price: 109.99,
    stock: 400,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM DDR5 32GB'),
    options: [
      { name: 'Speed', values: ['5600MHz', '6000MHz'] },
      { name: 'Color', values: ['Black', 'White'] },
    ],
    variants: [
      { optionValues: ['5600MHz', 'Black'], price: 109.99, stock: 100 },
      { optionValues: ['5600MHz', 'White'], price: 114.99, stock: 100 },
      { optionValues: ['6000MHz', 'Black'], price: 119.99, stock: 100 },
      { optionValues: ['6000MHz', 'White'], price: 124.99, stock: 100 },
    ],
  },
  {
    name: 'Trident Z5 RGB DDR5 64GB Kit',
    slug: 'trident-z5-rgb-ddr5-64gb',
    description: 'High-performance RGB DDR5 64GB.',
    price: 249.99,
    stock: 150,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM TridentZ5 64GB', 2),
    options: [{ name: 'Speed', values: ['6400MHz', '7200MHz'] }],
    variants: [
      { optionValues: ['6400MHz'], price: 249.99, stock: 100 },
      { optionValues: ['7200MHz'], price: 289.99, stock: 50 },
    ],
  },
  {
    name: 'Fury Beast DDR4 16GB Kit',
    slug: 'fury-beast-ddr4-16gb',
    description: 'Reliable DDR4 16GB kit.',
    price: 49.99,
    stock: 500,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM DDR4 16GB'),
  },
  {
    name: 'Dominator Platinum DDR5 32GB',
    slug: 'dominator-platinum-ddr5-32gb',
    description: 'Premium RGB DDR5 32GB.',
    price: 179.99,
    stock: 120,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM Dominator 32GB'),
  },
  {
    name: 'Ripjaws S5 DDR5 32GB Low Profile',
    slug: 'ripjaws-s5-ddr5-32gb-lp',
    description: 'Low profile DDR5 for compatibility.',
    price: 104.99,
    stock: 250,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM Ripjaws LP'),
  },
  {
    name: 'Vengeance DDR4 32GB Kit (2x16)',
    slug: 'vengeance-ddr4-32gb-kit',
    description: 'Solid DDR4 32GB performance.',
    price: 79.99,
    stock: 350,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM DDR4 32GB'),
  },
  {
    name: 'Flare X5 DDR5 32GB AMD EXPO',
    slug: 'flare-x5-ddr5-32gb-expo',
    description: 'DDR5 optimized for AMD EXPO.',
    price: 114.99,
    stock: 200,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM Flare X5'),
  },
  {
    name: 'Spectrix D50 DDR4 RGB 16GB',
    slug: 'spectrix-d50-ddr4-rgb-16gb',
    description: 'RGB DDR4 16GB module.',
    price: 54.99,
    stock: 180,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM Spectrix D50'),
  },
  {
    name: 'Crucial Pro DDR5 48GB Kit (2x24)',
    slug: 'crucial-pro-ddr5-48gb-kit',
    description: 'Non-binary capacity DDR5 kit.',
    price: 149.99,
    stock: 100,
    categorySlugs: ['memory-ram'],
    images: placeholderImg('RAM Crucial 48GB'),
  },
  {
    name: 'SO-DIMM DDR4 16GB Laptop RAM',
    slug: 'sodimm-ddr4-16gb-laptop',
    description: 'DDR4 RAM for laptops.',
    price: 39.99,
    stock: 300,
    categorySlugs: ['memory-ram', 'laptops'],
    images: placeholderImg('RAM SODIMM DDR4'),
  },
  {
    name: 'SO-DIMM DDR5 32GB Laptop RAM Kit',
    slug: 'sodimm-ddr5-32gb-laptop-kit',
    description: 'DDR5 RAM kit for laptops.',
    price: 129.99,
    stock: 150,
    categorySlugs: ['memory-ram', 'laptops'],
    images: placeholderImg('RAM SODIMM DDR5'),
  },

  // --- Storage (10+) ---
  {
    name: 'Samsung 990 Pro NVMe SSD',
    slug: 'samsung-990-pro-nvme-ssd',
    description: 'Top-tier Gen4 NVMe performance.',
    price: 79.99,
    stock: 300,
    categorySlugs: ['storage'],
    images: placeholderImg('SSD 990 Pro', 2),
    options: [{ name: 'Capacity', values: ['1TB', '2TB', '4TB'] }],
    variants: [
      { optionValues: ['1TB'], price: 79.99, stock: 150 },
      { optionValues: ['2TB'], price: 149.99, stock: 100 },
      { optionValues: ['4TB'], price: 289.99, stock: 50 },
    ],
  },
  {
    name: 'WD Black SN850X NVMe SSD',
    slug: 'wd-black-sn850x-nvme-ssd',
    description: 'Fast Gen4 NVMe SSD for gaming.',
    price: 74.99,
    stock: 400,
    categorySlugs: ['storage'],
    images: placeholderImg('SSD SN850X', 2),
    options: [{ name: 'Capacity', values: ['1TB', '2TB', '4TB'] }],
    variants: [
      { optionValues: ['1TB'], price: 74.99, stock: 200 },
      { optionValues: ['2TB'], price: 139.99, stock: 150 },
      { optionValues: ['4TB'], price: 279.99, stock: 50 },
    ],
  },
  {
    name: 'Crucial P5 Plus NVMe SSD',
    slug: 'crucial-p5-plus-nvme-ssd',
    description: 'Great value Gen4 NVMe SSD.',
    price: 59.99,
    stock: 500,
    categorySlugs: ['storage'],
    images: placeholderImg('SSD P5 Plus'),
    options: [{ name: 'Capacity', values: ['1TB', '2TB'] }],
    variants: [
      { optionValues: ['1TB'], price: 59.99, stock: 300 },
      { optionValues: ['2TB'], price: 109.99, stock: 200 },
    ],
  },
  {
    name: 'Samsung 870 EVO SATA SSD',
    slug: 'samsung-870-evo-sata-ssd',
    description: 'Reliable high-capacity SATA SSD.',
    price: 49.99,
    stock: 600,
    categorySlugs: ['storage'],
    images: placeholderImg('SSD 870 EVO'),
    options: [{ name: 'Capacity', values: ['500GB', '1TB', '2TB', '4TB'] }],
    variants: [
      { optionValues: ['500GB'], price: 49.99, stock: 200 },
      { optionValues: ['1TB'], price: 69.99, stock: 200 },
      { optionValues: ['2TB'], price: 129.99, stock: 150 },
      { optionValues: ['4TB'], price: 249.99, stock: 50 },
    ],
  },
  {
    name: 'Seagate Barracuda 4TB HDD',
    slug: 'seagate-barracuda-4tb-hdd',
    description: 'Popular 3.5" Desktop HDD.',
    price: 89.99,
    stock: 350,
    categorySlugs: ['storage'],
    images: placeholderImg('HDD Barracuda 4TB'),
  },
  {
    name: 'WD Red Pro 10TB NAS HDD',
    slug: 'wd-red-pro-10tb-nas-hdd',
    description: 'HDD designed for NAS systems.',
    price: 269.99,
    stock: 100,
    categorySlugs: ['storage', 'networking'],
    images: placeholderImg('HDD WD Red 10TB'),
  },
  {
    name: 'Sabrent Rocket 4 Plus NVMe',
    slug: 'sabrent-rocket-4-plus-nvme',
    description: 'High-endurance NVMe SSD.',
    price: 84.99,
    stock: 250,
    categorySlugs: ['storage'],
    images: placeholderImg('SSD Sabrent R4+'),
    options: [{ name: 'Capacity', values: ['1TB', '2TB'] }],
    variants: [
      { optionValues: ['1TB'], price: 84.99, stock: 150 },
      { optionValues: ['2TB'], price: 154.99, stock: 100 },
    ],
  },
  {
    name: 'Kingston NV2 NVMe SSD',
    slug: 'kingston-nv2-nvme-ssd',
    description: 'Budget-friendly NVMe SSD.',
    price: 49.99,
    stock: 700,
    categorySlugs: ['storage'],
    images: placeholderImg('SSD Kingston NV2'),
    options: [{ name: 'Capacity', values: ['500GB', '1TB', '2TB'] }],
    variants: [
      { optionValues: ['500GB'], price: 49.99, stock: 300 },
      { optionValues: ['1TB'], price: 64.99, stock: 250 },
      { optionValues: ['2TB'], price: 119.99, stock: 150 },
    ],
  },
  {
    name: 'External SSD T7 Shield 2TB',
    slug: 'external-ssd-t7-shield-2tb',
    description: 'Rugged external USB-C SSD.',
    price: 149.99,
    stock: 180,
    categorySlugs: ['storage'],
    images: placeholderImg('SSD Ext T7 2TB', 2),
  },
  {
    name: 'External HDD Expansion 5TB',
    slug: 'external-hdd-expansion-5tb',
    description: 'Large capacity external USB HDD.',
    price: 109.99,
    stock: 220,
    categorySlugs: ['storage'],
    images: placeholderImg('HDD Ext 5TB'),
  },

  // --- Video Cards (GPUs) (10+) ---
  {
    name: 'NVIDIA GeForce RTX 4090 Founders Edition',
    slug: 'nvidia-rtx-4090-fe',
    description: 'The ultimate gaming GPU.',
    price: 1599.0,
    stock: 30,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU RTX 4090 FE', 3),
  },
  {
    name: 'ASUS ROG Strix RTX 4080 Super OC',
    slug: 'asus-strix-rtx-4080-super-oc',
    description: 'Top-tier custom RTX 4080 Super.',
    price: 1249.99,
    stock: 50,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU Strix 4080S', 2),
  },
  {
    name: 'Gigabyte Gaming OC RTX 4070 Ti Super',
    slug: 'gigabyte-rtx-4070-ti-super',
    description: 'Excellent 1440p/4K GPU.',
    price: 849.99,
    stock: 100,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU 4070TiS OC'),
  },
  {
    name: 'MSI Ventus 3X OC RTX 4070 Super',
    slug: 'msi-rtx-4070-super-ventus',
    description: 'Great value RTX 4070 Super.',
    price: 609.99,
    stock: 150,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU 4070S Ventus'),
  },
  {
    name: 'AMD Radeon RX 7900 XTX Reference',
    slug: 'amd-radeon-rx-7900-xtx',
    description: 'AMD flagship GPU.',
    price: 949.99,
    stock: 60,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU RX 7900XTX', 2),
  },
  {
    name: 'Sapphire Pulse RX 7800 XT',
    slug: 'sapphire-pulse-rx-7800-xt',
    description: 'Popular custom RX 7800 XT.',
    price: 519.99,
    stock: 120,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU Pulse 7800XT'),
  },
  {
    name: 'PowerColor Hellhound RX 7700 XT',
    slug: 'powercolor-hellhound-rx-7700-xt',
    description: 'Solid 1440p AMD GPU.',
    price: 439.99,
    stock: 140,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU Hellhound 7700XT'),
  },
  {
    name: 'NVIDIA GeForce RTX 4060 Ti 8GB',
    slug: 'nvidia-rtx-4060-ti-8gb',
    description: 'Mid-range 1080p/1440p GPU.',
    price: 399.0,
    stock: 200,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU RTX 4060Ti'),
  },
  {
    name: 'AMD Radeon RX 6650 XT',
    slug: 'amd-radeon-rx-6650-xt',
    description: 'Great value 1080p GPU.',
    price: 249.99,
    stock: 250,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU RX 6650XT'),
  },
  {
    name: 'Intel Arc A770 16GB Limited Edition',
    slug: 'intel-arc-a770-16gb-le',
    description: "Intel's top Arc GPU.",
    price: 329.99,
    stock: 90,
    categorySlugs: ['video-cards-gpus'],
    images: placeholderImg('GPU Arc A770', 2),
  },

  // --- Power Supplies (PSUs) (10+) ---
  {
    name: 'Corsair RM1000e 1000W Gold ATX 3.0',
    slug: 'corsair-rm1000e-atx3',
    description: '1000W Gold PSU with ATX 3.0.',
    price: 179.99,
    stock: 150,
    categorySlugs: ['power-supplies-psus'],
    images: placeholderImg('PSU RM1000e', 2),
  },
  {
    name: 'SeaSonic FOCUS Plus Gold 850W',
    slug: 'seasonic-focus-plus-gold-850w',
    description: 'Highly rated 850W Gold PSU.',
    price: 149.99,
    stock: 200,
    categorySlugs: ['power-supplies-psus'],
    images: placeholderImg('PSU Focus+ 850W'),
  },
  {
    name: 'EVGA SuperNOVA 750 G6 Gold',
    slug: 'evga-supernova-750-g6',
    description: 'Reliable 750W Gold PSU.',
    price: 119.99,
    stock: 250,
    categorySlugs: ['power-supplies-psus'],
    images: placeholderImg('PSU EVGA 750 G6'),
  },
  {
    name: 'Cooler Master V850 SFX Gold',
    slug: 'cooler-master-v850-sfx',
    description: 'High power SFX PSU.',
    price: 159.99,
    stock: 100,
    categorySlugs: ['power-supplies-psus', 'pc-cases'],
    images: placeholderImg('PSU V850 SFX'),
  },
  {
    name: 'Thermaltake Toughpower GF3 1200W Gold',
    slug: 'thermaltake-gf3-1200w',
    description: '1200W ATX 3.0 PSU.',
    price: 219.99,
    stock: 80,
    categorySlugs: ['power-supplies-psus'],
    images: placeholderImg('PSU GF3 1200W'),
  },
  {
    name: 'be quiet! Pure Power 12 M 650W Bronze',
    slug: 'bequiet-pure-power-12m-650w',
    description: 'Quiet 650W Bronze PSU.',
    price: 89.99,
    stock: 300,
    categorySlugs: ['power-supplies-psus'],
    images: placeholderImg('PSU PurePower 650W'),
  },
  {
    name: 'Corsair SF750 Platinum SFX',
    slug: 'corsair-sf750-platinum',
    description: 'Premium 750W SFX PSU.',
    price: 189.99,
    stock: 120,
    categorySlugs: ['power-supplies-psus', 'pc-cases'],
    images: placeholderImg('PSU SF750 Plat'),
  },
  {
    name: 'MSI MPG A1000G PCIE5 1000W Gold',
    slug: 'msi-mpg-a1000g-pcie5',
    description: 'MSI 1000W ATX 3.0 PSU.',
    price: 199.99,
    stock: 110,
    categorySlugs: ['power-supplies-psus'],
    images: placeholderImg('PSU MSI 1000W'),
  },
  {
    name: 'Antec NeoECO Gold Zen 500W',
    slug: 'antec-necoeco-gold-zen-500w',
    description: 'Budget 500W Gold PSU.',
    price: 69.99,
    stock: 180,
    categorySlugs: ['power-supplies-psus'],
    images: placeholderImg('PSU Antec 500W'),
  },
  {
    name: 'SilverStone SX1000 Platinum SFX-L',
    slug: 'silverstone-sx1000-sfxl',
    description: '1000W Platinum SFX-L PSU.',
    price: 299.99,
    stock: 60,
    categorySlugs: ['power-supplies-psus', 'pc-cases'],
    images: placeholderImg('PSU SX1000 SFXL'),
  },

  // --- PC Cases (10+) ---
  {
    name: 'Fractal Design Meshify 2 Compact',
    slug: 'fractal-meshify-2-compact',
    description: 'High airflow compact ATX case.',
    price: 129.99,
    stock: 150,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case Meshify 2C', 2),
    options: [{ name: 'Color', values: ['Black', 'White', 'Gray'] }],
    variants: [
      { optionValues: ['Black'], price: 129.99, stock: 70 },
      { optionValues: ['White'], price: 134.99, stock: 50 },
      { optionValues: ['Gray'], price: 129.99, stock: 30 },
    ],
  },
  {
    name: 'Lian Li Lancool III RGB',
    slug: 'lian-li-lancool-iii-rgb',
    description: 'Spacious high-airflow ATX case.',
    price: 169.99,
    stock: 100,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case Lancool III', 2),
    options: [{ name: 'Color', values: ['Black', 'White'] }],
    variants: [
      { optionValues: ['Black'], price: 169.99, stock: 60 },
      { optionValues: ['White'], price: 174.99, stock: 40 },
    ],
  },
  {
    name: 'NZXT H5 Flow',
    slug: 'nzxt-h5-flow',
    description: 'Clean mid-tower ATX case.',
    price: 94.99,
    stock: 250,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case H5 Flow'),
    options: [{ name: 'Color', values: ['Black', 'White'] }],
    variants: [
      { optionValues: ['Black'], price: 94.99, stock: 150 },
      { optionValues: ['White'], price: 94.99, stock: 100 },
    ],
  },
  {
    name: 'Cooler Master MasterBox Q300L',
    slug: 'cm-masterbox-q300l',
    description: 'Popular budget mATX case.',
    price: 49.99,
    stock: 300,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case Q300L'),
  },
  {
    name: 'Phanteks Eclipse G360A',
    slug: 'phanteks-eclipse-g360a',
    description: 'Mid-tower with great airflow and RGB.',
    price: 89.99,
    stock: 180,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case G360A'),
    options: [{ name: 'Color', values: ['Black', 'White'] }],
    variants: [
      { optionValues: ['Black'], price: 89.99, stock: 100 },
      { optionValues: ['White'], price: 94.99, stock: 80 },
    ],
  },
  {
    name: 'HYTE Y60 Panoramic ATX',
    slug: 'hyte-y60-panoramic',
    description: 'Unique panoramic view ATX case.',
    price: 199.99,
    stock: 90,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case Hyte Y60', 3),
    options: [{ name: 'Color', values: ['Black', 'White', 'Red'] }],
    variants: [
      { optionValues: ['Black'], price: 199.99, stock: 40 },
      { optionValues: ['White'], price: 199.99, stock: 30 },
      { optionValues: ['Red'], price: 199.99, stock: 20 },
    ],
  },
  {
    name: 'Corsair 4000D Airflow',
    slug: 'corsair-4000d-airflow',
    description: 'Best-selling mid-tower airflow case.',
    price: 104.99,
    stock: 400,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case 4000D Airflow'),
    options: [{ name: 'Color', values: ['Black', 'White'] }],
    variants: [
      { optionValues: ['Black'], price: 104.99, stock: 250 },
      { optionValues: ['White'], price: 104.99, stock: 150 },
    ],
  },
  {
    name: 'Fractal Design Torrent Compact',
    slug: 'fractal-torrent-compact',
    description: 'Airflow-focused case with large fans.',
    price: 149.99,
    stock: 110,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case Torrent Compact'),
  },
  {
    name: 'Thermaltake Core P3 Open Frame',
    slug: 'thermaltake-core-p3',
    description: 'Wall-mountable open frame case.',
    price: 139.99,
    stock: 70,
    categorySlugs: ['pc-cases'],
    images: placeholderImg('Case Core P3'),
  },
  {
    name: 'Cooler Master NR200P MAX SFF',
    slug: 'cm-nr200p-max',
    description: 'Premium SFF case with PSU/AIO.',
    price: 349.99,
    stock: 60,
    categorySlugs: ['pc-cases', 'power-supplies-psus', 'pc-cooling'],
    images: placeholderImg('Case NR200P Max', 2),
  },

  // --- Monitors (10+) ---
  {
    name: 'Alienware AW3423DWF 34" QD-OLED',
    slug: 'alienware-aw3423dwf-qdoled',
    description: 'Stunning ultrawide QD-OLED.',
    price: 999.99,
    stock: 80,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor AW34 OLED', 2),
  },
  {
    name: 'LG UltraGear 27GP850-B 27" 1440p 165Hz',
    slug: 'lg-ultragear-27gp850b',
    description: 'Popular 1440p high refresh rate monitor.',
    price: 349.99,
    stock: 250,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor LG 27GP850'),
  },
  {
    name: 'Gigabyte M32U 32" 4K 144Hz',
    slug: 'gigabyte-m32u-4k-144hz',
    description: 'Great value 4K high refresh rate monitor.',
    price: 699.99,
    stock: 120,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor M32U 4K'),
  },
  {
    name: 'Samsung Odyssey Neo G9 49" Super Ultrawide',
    slug: 'samsung-neo-g9-49',
    description: 'Immense super ultrawide gaming.',
    price: 1799.99,
    stock: 40,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor Neo G9', 3),
  },
  {
    name: 'Dell UltraSharp U2723QE 27" 4K USB-C Hub',
    slug: 'dell-u2723qe-4k-hub',
    description: 'Productivity 4K monitor with hub.',
    price: 579.99,
    stock: 180,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor Dell U2723QE'),
  },
  {
    name: 'ASUS TUF Gaming VG249Q1A 24" 1080p 165Hz',
    slug: 'asus-tuf-vg249q1a',
    description: 'Budget 1080p high refresh monitor.',
    price: 189.99,
    stock: 300,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor TUF VG249'),
  },
  {
    name: 'BenQ MOBIUZ EX2710Q 27" 1440p 165Hz',
    slug: 'benq-mobiuz-ex2710q',
    description: 'Console-focused 1440p monitor.',
    price: 299.99,
    stock: 200,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor BenQ EX2710Q'),
  },
  {
    name: 'Acer Predator XB273U GX 27" 1440p 240Hz',
    slug: 'acer-predator-xb273u-gx',
    description: 'High refresh 1440p esports monitor.',
    price: 499.99,
    stock: 110,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor Predator 27'),
  },
  {
    name: 'ViewSonic VX2768-2KP-MHD 27" 1440p 144Hz',
    slug: 'viewsonic-vx2768-1440p',
    description: 'Value 1440p 144Hz IPS monitor.',
    price: 219.99,
    stock: 280,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor ViewSonic VX27'),
  },
  {
    name: 'LG C3 42" OLED Evo TV/Monitor',
    slug: 'lg-c3-42-oled',
    description: 'OLED TV usable as a large monitor.',
    price: 899.99,
    stock: 70,
    categorySlugs: ['monitors'],
    images: placeholderImg('Monitor LG C3 42', 2),
  },

  // --- Keyboards (10+) ---
  {
    name: 'Logitech G Pro X TKL Lightspeed',
    slug: 'logitech-gpro-x-tkl',
    description: 'Wireless TKL gaming keyboard.',
    price: 199.99,
    stock: 150,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD GPro X TKL', 2),
    options: [{ name: 'Switch', values: ['GX Brown', 'GX Red', 'GX Blue'] }],
    variants: [
      { optionValues: ['GX Brown'], price: 199.99, stock: 60 },
      { optionValues: ['GX Red'], price: 199.99, stock: 60 },
      { optionValues: ['GX Blue'], price: 199.99, stock: 30 },
    ],
  },
  {
    name: 'Razer Huntsman V3 Pro TKL Analog',
    slug: 'razer-huntsman-v3-pro-tkl',
    description: 'Analog optical switch TKL.',
    price: 219.99,
    stock: 100,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD Huntsman V3 Pro'),
  },
  {
    name: 'Keychron Q1 Pro QMK/VIA Wireless Custom',
    slug: 'keychron-q1-pro-wireless',
    description: 'Customizable wireless 75% keyboard.',
    price: 199.0,
    stock: 120,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD Keychron Q1 Pro', 3),
    options: [
      { name: 'Color', values: ['Carbon Black', 'Shell White'] },
      { name: 'Switch', values: ['K Pro Brown', 'K Pro Red', 'K Pro Banana'] },
    ],
    variants: [
      { optionValues: ['Carbon Black', 'K Pro Brown'], price: 199.0, stock: 30 },
      { optionValues: ['Carbon Black', 'K Pro Red'], price: 199.0, stock: 30 },
      { optionValues: ['Shell White', 'K Pro Brown'], price: 199.0, stock: 30 },
      { optionValues: ['Shell White', 'K Pro Banana'], price: 199.0, stock: 30 },
    ],
  },
  {
    name: 'SteelSeries Apex Pro TKL (2023)',
    slug: 'steelseries-apex-pro-tkl-2023',
    description: 'Adjustable actuation TKL.',
    price: 189.99,
    stock: 140,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD Apex Pro TKL'),
  },
  {
    name: 'Corsair K70 RGB MK.2',
    slug: 'corsair-k70-rgb-mk2',
    description: 'Full-size RGB mechanical keyboard.',
    price: 159.99,
    stock: 200,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD K70 MK2'),
    options: [{ name: 'Switch', values: ['Cherry MX Red', 'Cherry MX Brown', 'Cherry MX Speed'] }],
    variants: [
      { optionValues: ['Cherry MX Red'], price: 159.99, stock: 80 },
      { optionValues: ['Cherry MX Brown'], price: 159.99, stock: 70 },
      { optionValues: ['Cherry MX Speed'], price: 164.99, stock: 50 },
    ],
  },
  {
    name: 'Logitech MX Keys S Wireless',
    slug: 'logitech-mx-keys-s',
    description: 'Premium wireless productivity keyboard.',
    price: 119.99,
    stock: 300,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD MX Keys S'),
    options: [{ name: 'Color', values: ['Graphite', 'Pale Gray'] }],
    variants: [
      { optionValues: ['Graphite'], price: 119.99, stock: 200 },
      { optionValues: ['Pale Gray'], price: 119.99, stock: 100 },
    ],
  },
  {
    name: 'Ducky One 3 Mini 60%',
    slug: 'ducky-one-3-mini',
    description: 'Popular 60% mechanical keyboard.',
    price: 119.0,
    stock: 160,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD Ducky One 3 Mini'),
  },
  {
    name: 'RK ROYAL KLUDGE RK61 Wireless 60%',
    slug: 'rk-royal-kludge-rk61',
    description: 'Budget wireless 60% keyboard.',
    price: 49.99,
    stock: 400,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD RK61'),
  },
  {
    name: 'Microsoft Ergonomic Keyboard',
    slug: 'microsoft-ergonomic-keyboard',
    description: 'Wired ergonomic keyboard.',
    price: 59.99,
    stock: 250,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD MS Ergonomic'),
  },
  {
    name: 'Akko 3068B Plus Prunus Lannesiana',
    slug: 'akko-3068b-plus-prunus',
    description: 'Stylish 65% wireless keyboard.',
    price: 89.99,
    stock: 130,
    categorySlugs: ['keyboards'],
    images: placeholderImg('KBD Akko 3068B', 2),
  },

  // --- Mice (10+) ---
  {
    name: 'Logitech G Pro X Superlight 2 Wireless',
    slug: 'logitech-gpx-superlight-2',
    description: 'Ultra-lightweight wireless gaming mouse.',
    price: 159.0,
    stock: 200,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse GPX 2', 2),
    options: [{ name: 'Color', values: ['Black', 'White', 'Pink'] }],
    variants: [
      { optionValues: ['Black'], price: 159.0, stock: 100 },
      { optionValues: ['White'], price: 159.0, stock: 70 },
      { optionValues: ['Pink'], price: 159.0, stock: 30 },
    ],
  },
  {
    name: 'Razer DeathAdder V3 Pro Wireless',
    slug: 'razer-deathadder-v3-pro',
    description: 'Ergonomic lightweight wireless mouse.',
    price: 149.99,
    stock: 180,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse DeathAdder V3 Pro'),
    options: [{ name: 'Color', values: ['Black', 'White'] }],
    variants: [
      { optionValues: ['Black'], price: 149.99, stock: 100 },
      { optionValues: ['White'], price: 149.99, stock: 80 },
    ],
  },
  {
    name: 'Logitech MX Master 3S Wireless',
    slug: 'logitech-mx-master-3s',
    description: 'Top productivity wireless mouse.',
    price: 99.99,
    stock: 350,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse MX Master 3S'),
    options: [{ name: 'Color', values: ['Graphite', 'Pale Gray'] }],
    variants: [
      { optionValues: ['Graphite'], price: 99.99, stock: 250 },
      { optionValues: ['Pale Gray'], price: 99.99, stock: 100 },
    ],
  },
  {
    name: 'SteelSeries Aerox 5 Wireless',
    slug: 'steelseries-aerox-5-wireless',
    description: 'Lightweight multi-genre wireless mouse.',
    price: 139.99,
    stock: 160,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse Aerox 5 WL'),
  },
  {
    name: 'Pulsar X2V2 Wireless Gaming Mouse',
    slug: 'pulsar-x2v2-wireless',
    description: 'Popular lightweight symmetrical mouse.',
    price: 99.95,
    stock: 140,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse Pulsar X2V2'),
    options: [{ name: 'Size', values: ['Medium', 'Mini'] }],
    variants: [
      { optionValues: ['Medium'], price: 99.95, stock: 80 },
      { optionValues: ['Mini'], price: 99.95, stock: 60 },
    ],
  },
  {
    name: 'Glorious Model O Wireless',
    slug: 'glorious-model-o-wireless',
    description: 'Lightweight honeycomb wireless mouse.',
    price: 79.99,
    stock: 220,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse Model O WL'),
    options: [{ name: 'Color', values: ['Matte Black', 'Matte White'] }],
    variants: [
      { optionValues: ['Matte Black'], price: 79.99, stock: 120 },
      { optionValues: ['Matte White'], price: 79.99, stock: 100 },
    ],
  },
  {
    name: 'Razer Viper Mini Signature Edition',
    slug: 'razer-viper-mini-se',
    description: 'Ultra-premium lightweight mouse.',
    price: 279.99,
    stock: 50,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse Viper Mini SE', 2),
  },
  {
    name: 'Logitech G502 X Lightspeed Wireless',
    slug: 'logitech-g502-x-lightspeed',
    description: 'Iconic shape, updated wireless.',
    price: 139.99,
    stock: 250,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse G502 X WL'),
  },
  {
    name: 'Microsoft Classic IntelliMouse',
    slug: 'microsoft-classic-intellimouse',
    description: 'Modern take on a classic shape.',
    price: 39.99,
    stock: 300,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse IntelliMouse'),
  },
  {
    name: 'Logitech MX Vertical Ergonomic Mouse',
    slug: 'logitech-mx-vertical',
    description: 'Vertical mouse for ergonomics.',
    price: 99.99,
    stock: 150,
    categorySlugs: ['mice'],
    images: placeholderImg('Mouse MX Vertical'),
  },

  // --- Headsets & Audio (10+) ---
  {
    name: 'SteelSeries Arctis Nova Pro Wireless',
    slug: 'steelseries-arctis-nova-pro-wl',
    description: 'Top-tier wireless gaming headset.',
    price: 349.99,
    stock: 100,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('HS Nova Pro WL', 2),
    options: [{ name: 'Platform', values: ['PC/Playstation', 'Xbox'] }],
    variants: [
      { optionValues: ['PC/Playstation'], price: 349.99, stock: 60 },
      { optionValues: ['Xbox'], price: 349.99, stock: 40 },
    ],
  },
  {
    name: 'Logitech G Pro X 2 Lightspeed Wireless',
    slug: 'logitech-gpro-x-2-wl',
    description: 'Pro-level wireless gaming headset.',
    price: 249.99,
    stock: 150,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('HS GPro X 2 WL'),
  },
  {
    name: 'Razer BlackShark V2 Pro Wireless (2023)',
    slug: 'razer-blackshark-v2-pro-2023',
    description: 'Excellent wireless headset.',
    price: 199.99,
    stock: 180,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('HS BlackShark V2 Pro'),
  },
  {
    name: 'HyperX Cloud III Wireless',
    slug: 'hyperx-cloud-iii-wireless',
    description: 'Comfortable wireless gaming headset.',
    price: 169.99,
    stock: 200,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('HS Cloud III WL'),
  },
  {
    name: 'Corsair HS80 RGB Wireless',
    slug: 'corsair-hs80-rgb-wireless',
    description: 'Comfortable Dolby Atmos headset.',
    price: 149.99,
    stock: 220,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('HS HS80 RGB WL'),
  },
  {
    name: 'Sennheiser HD 560S Audiophile Headphones',
    slug: 'sennheiser-hd-560s',
    description: 'Open-back headphones for critical listening.',
    price: 199.95,
    stock: 130,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('HP HD 560S'),
  },
  {
    name: 'Shure MV7 USB/XLR Dynamic Microphone',
    slug: 'shure-mv7-mic',
    description: 'Versatile podcasting microphone.',
    price: 249.0,
    stock: 90,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('Mic Shure MV7', 2),
    options: [{ name: 'Color', values: ['Black', 'Silver'] }],
    variants: [
      { optionValues: ['Black'], price: 249.0, stock: 50 },
      { optionValues: ['Silver'], price: 249.0, stock: 40 },
    ],
  },
  {
    name: 'Elgato Wave:3 USB Condenser Microphone',
    slug: 'elgato-wave-3-mic',
    description: 'Popular streaming microphone.',
    price: 149.99,
    stock: 170,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('Mic Wave 3'),
  },
  {
    name: 'Logitech Z407 Bluetooth Computer Speakers',
    slug: 'logitech-z407-speakers',
    description: '2.1 speaker system with subwoofer.',
    price: 99.99,
    stock: 250,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('SPK Z407'),
  },
  {
    name: 'Audioengine A2+ Wireless Bookshelf Speakers',
    slug: 'audioengine-a2-plus-wireless',
    description: 'Premium compact wireless speakers.',
    price: 269.0,
    stock: 110,
    categorySlugs: ['headsets-audio'],
    images: placeholderImg('SPK A2+ WL', 2),
  },

  // --- Webcams (10+) ---
  {
    name: 'Logitech C920x Pro HD Webcam',
    slug: 'logitech-c920x-pro',
    description: 'The standard 1080p webcam.',
    price: 69.99,
    stock: 500,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC C920x'),
  },
  {
    name: 'Logitech Brio 4K Webcam',
    slug: 'logitech-brio-4k',
    description: 'Premium 4K webcam with HDR.',
    price: 199.99,
    stock: 150,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC Brio 4K', 2),
  },
  {
    name: 'Razer Kiyo Pro Webcam',
    slug: 'razer-kiyo-pro',
    description: 'High-performance low-light webcam.',
    price: 199.99,
    stock: 120,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC Kiyo Pro'),
  },
  {
    name: 'Elgato Facecam Pro 4K60',
    slug: 'elgato-facecam-pro',
    description: 'Uncompressed 4K60 webcam for creators.',
    price: 299.99,
    stock: 80,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC Facecam Pro', 2),
  },
  {
    name: 'Anker PowerConf C300 Smart AI Webcam',
    slug: 'anker-powerconf-c300',
    description: 'AI-powered 1080p webcam.',
    price: 129.99,
    stock: 180,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC Anker C300'),
  },
  {
    name: 'NexiGo N60 1080p Webcam with Privacy Cover',
    slug: 'nexigo-n60-1080p',
    description: 'Budget 1080p webcam.',
    price: 39.99,
    stock: 400,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC NexiGo N60'),
  },
  {
    name: 'Logitech StreamCam',
    slug: 'logitech-streamcam',
    description: 'Webcam designed for streaming.',
    price: 169.99,
    stock: 200,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC StreamCam'),
    options: [{ name: 'Color', values: ['Graphite', 'White'] }],
    variants: [
      { optionValues: ['Graphite'], price: 169.99, stock: 120 },
      { optionValues: ['White'], price: 169.99, stock: 80 },
    ],
  },
  {
    name: 'OBSBOT Tiny 2 AI-Powered 4K PTZ Webcam',
    slug: 'obsbot-tiny-2-4k-ptz',
    description: 'AI tracking PTZ webcam.',
    price: 329.0,
    stock: 60,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC OBSBOT Tiny 2', 2),
  },
  {
    name: 'Dell UltraSharp WB7022 4K Webcam',
    slug: 'dell-wb7022-4k',
    description: 'High-quality Dell 4K webcam.',
    price: 234.99,
    stock: 90,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC Dell 4K'),
  },
  {
    name: 'Logitech C270 HD Webcam (720p)',
    slug: 'logitech-c270-hd',
    description: 'Basic 720p webcam.',
    price: 24.99,
    stock: 600,
    categorySlugs: ['webcams'],
    images: placeholderImg('WC C270'),
  },

  // --- Laptops (10+) ---
  {
    name: 'Apple MacBook Pro 14" M3 Pro',
    slug: 'apple-macbook-pro-14-m3-pro',
    description: 'Powerful Apple Silicon laptop.',
    price: 1999.0,
    stock: 100,
    categorySlugs: ['laptops'],
    images: placeholderImg('Laptop MBP 14 M3 Pro', 2),
    options: [
      { name: 'Color', values: ['Space Black', 'Silver'] },
      { name: 'RAM/Storage', values: ['18GB/512GB', '18GB/1TB', '36GB/1TB'] },
    ],
    variants: [
      { optionValues: ['Space Black', '18GB/512GB'], price: 1999.0, stock: 30 },
      { optionValues: ['Silver', '18GB/512GB'], price: 1999.0, stock: 30 },
      { optionValues: ['Space Black', '18GB/1TB'], price: 2199.0, stock: 20 },
      { optionValues: ['Space Black', '36GB/1TB'], price: 2599.0, stock: 20 },
    ],
  },
  {
    name: 'Apple MacBook Air 13" M3',
    slug: 'apple-macbook-air-13-m3',
    description: 'Thin and light Apple laptop.',
    price: 1099.0,
    stock: 150,
    categorySlugs: ['laptops'],
    images: placeholderImg('Laptop MBA 13 M3', 2),
    options: [
      { name: 'Color', values: ['Midnight', 'Starlight', 'Space Gray', 'Silver'] },
      { name: 'RAM/Storage', values: ['8GB/256GB', '8GB/512GB', '16GB/512GB'] },
    ],
    variants: [
      { optionValues: ['Midnight', '8GB/256GB'], price: 1099.0, stock: 40 },
      { optionValues: ['Space Gray', '8GB/512GB'], price: 1299.0, stock: 40 },
      { optionValues: ['Silver', '8GB/512GB'], price: 1299.0, stock: 40 },
      { optionValues: ['Midnight', '16GB/512GB'], price: 1499.0, stock: 30 },
    ],
  },
  {
    name: 'Dell XPS 15 Laptop (9530)',
    slug: 'dell-xps-15-9530',
    description: 'Premium Windows ultrabook.',
    price: 1499.0,
    stock: 120,
    categorySlugs: ['laptops'],
    images: placeholderImg('Laptop XPS 15'),
    options: [
      { name: 'Config', values: ['i7/16GB/512GB/FHD', 'i7/16GB/1TB/OLED', 'i9/32GB/1TB/OLED'] },
    ],
    variants: [
      { optionValues: ['i7/16GB/512GB/FHD'], price: 1499.0, stock: 50 },
      { optionValues: ['i7/16GB/1TB/OLED'], price: 1899.0, stock: 40 },
      { optionValues: ['i9/32GB/1TB/OLED'], price: 2399.0, stock: 30 },
    ],
  },
  {
    name: 'ASUS ROG Zephyrus G14 Gaming Laptop',
    slug: 'asus-rog-zephyrus-g14',
    description: 'Powerful and portable gaming laptop.',
    price: 1599.99,
    stock: 90,
    categorySlugs: ['laptops', 'video-cards-gpus'],
    images: placeholderImg('Laptop Zephyrus G14', 2),
    options: [{ name: 'GPU', values: ['RTX 4060', 'RTX 4070'] }],
    variants: [
      { optionValues: ['RTX 4060'], price: 1599.99, stock: 50 },
      { optionValues: ['RTX 4070'], price: 1849.99, stock: 40 },
    ],
  },
  {
    name: 'Lenovo Legion Pro 5i Gen 8 Gaming Laptop',
    slug: 'lenovo-legion-pro-5i-gen8',
    description: 'High-performance gaming laptop.',
    price: 1449.99,
    stock: 110,
    categorySlugs: ['laptops', 'video-cards-gpus'],
    images: placeholderImg('Laptop Legion 5i Pro'),
  },
  {
    name: 'HP Spectre x360 14 2-in-1 Laptop',
    slug: 'hp-spectre-x360-14',
    description: 'Premium convertible Windows laptop.',
    price: 1399.99,
    stock: 130,
    categorySlugs: ['laptops'],
    images: placeholderImg('Laptop Spectre x360'),
  },
  {
    name: 'Acer Aspire 5 Slim Laptop',
    slug: 'acer-aspire-5-slim',
    description: 'Budget-friendly everyday laptop.',
    price: 379.99,
    stock: 250,
    categorySlugs: ['laptops'],
    images: placeholderImg('Laptop Aspire 5'),
  },
  {
    name: 'Microsoft Surface Laptop 5 13.5"',
    slug: 'microsoft-surface-laptop-5-13',
    description: 'Sleek Windows laptop.',
    price: 999.99,
    stock: 160,
    categorySlugs: ['laptops'],
    images: placeholderImg('Laptop Surface 5'),
    options: [{ name: 'Color', values: ['Platinum', 'Matte Black', 'Sage'] }],
    variants: [
      { optionValues: ['Platinum'], price: 999.99, stock: 70 },
      { optionValues: ['Matte Black'], price: 999.99, stock: 50 },
      { optionValues: ['Sage'], price: 999.99, stock: 40 },
    ],
  },
  {
    name: 'Framework Laptop 13 (DIY Edition)',
    slug: 'framework-laptop-13-diy',
    description: 'Modular and repairable laptop.',
    price: 849.0,
    stock: 80,
    categorySlugs: ['laptops', 'components'],
    images: placeholderImg('Laptop Framework 13', 2),
  },
  {
    name: 'Razer Blade 16 Gaming Laptop',
    slug: 'razer-blade-16',
    description: 'Premium gaming laptop with dual-mode display.',
    price: 2699.99,
    stock: 60,
    categorySlugs: ['laptops', 'video-cards-gpus'],
    images: placeholderImg('Laptop Blade 16'),
  },

  // --- Desktops (10+) ---
  {
    name: 'Apple iMac 24" M3',
    slug: 'apple-imac-24-m3',
    description: 'All-in-one Apple desktop.',
    price: 1299.0,
    stock: 120,
    categorySlugs: ['desktops'],
    images: placeholderImg('Desktop iMac 24 M3', 2),
    options: [
      { name: 'Color', values: ['Blue', 'Green', 'Pink', 'Silver', 'Yellow', 'Orange', 'Purple'] },
      { name: 'Config', values: ['8GPU/8GB/256GB', '10GPU/8GB/512GB', '10GPU/16GB/1TB'] },
    ],
    variants: [
      { optionValues: ['Blue', '8GPU/8GB/256GB'], price: 1299.0, stock: 20 },
      { optionValues: ['Silver', '10GPU/8GB/512GB'], price: 1499.0, stock: 20 },
      { optionValues: ['Green', '10GPU/8GB/512GB'], price: 1499.0, stock: 20 },
      { optionValues: ['Blue', '10GPU/16GB/1TB'], price: 1899.0, stock: 10 },
      { optionValues: ['Pink', '8GPU/8GB/256GB'], price: 1299.0, stock: 15 },
      { optionValues: ['Yellow', '8GPU/8GB/256GB'], price: 1299.0, stock: 15 },
      { optionValues: ['Purple', '10GPU/16GB/1TB'], price: 1899.0, stock: 10 },
    ],
  },
  {
    name: 'Dell XPS Desktop (8960)',
    slug: 'dell-xps-desktop-8960',
    description: 'Powerful and compact desktop PC.',
    price: 1249.99,
    stock: 100,
    categorySlugs: ['desktops'],
    images: placeholderImg('Desktop XPS 8960'),
  },
  {
    name: 'HP Envy Desktop PC',
    slug: 'hp-envy-desktop',
    description: 'Stylish desktop for home and office.',
    price: 899.99,
    stock: 150,
    categorySlugs: ['desktops'],
    images: placeholderImg('Desktop HP Envy'),
  },
  {
    name: 'Alienware Aurora R16 Gaming Desktop',
    slug: 'alienware-aurora-r16',
    description: 'High-performance pre-built gaming PC.',
    price: 1649.99,
    stock: 80,
    categorySlugs: ['desktops', 'cpus', 'video-cards-gpus'],
    images: placeholderImg('Desktop Aurora R16', 2),
  },
  {
    name: 'CyberPowerPC Gamer Xtreme VR Gaming PC',
    slug: 'cyberpowerpc-gamer-xtreme-vr',
    description: 'Popular mid-range gaming desktop.',
    price: 1199.99,
    stock: 130,
    categorySlugs: ['desktops', 'cpus', 'video-cards-gpus'],
    images: placeholderImg('Desktop CyberPowerPC'),
  },
  {
    name: 'Apple Mac Mini M2',
    slug: 'apple-mac-mini-m2',
    description: 'Compact and affordable Mac desktop.',
    price: 599.0,
    stock: 200,
    categorySlugs: ['desktops'],
    images: placeholderImg('Desktop Mac Mini M2'),
    options: [{ name: 'Config', values: ['8GB/256GB', '8GB/512GB', '16GB/1TB'] }],
    variants: [
      { optionValues: ['8GB/256GB'], price: 599.0, stock: 100 },
      { optionValues: ['8GB/512GB'], price: 799.0, stock: 60 },
      { optionValues: ['16GB/1TB'], price: 1199.0, stock: 40 },
    ],
  },
  {
    name: 'Lenovo IdeaCentre Mini 5i',
    slug: 'lenovo-ideacentre-mini-5i',
    description: 'Compact Windows mini PC.',
    price: 499.99,
    stock: 140,
    categorySlugs: ['desktops'],
    images: placeholderImg('Desktop IdeaCentre Mini'),
  },
  {
    name: 'MSI Trident AS Gaming Desktop',
    slug: 'msi-trident-as',
    description: 'Compact gaming desktop.',
    price: 1399.99,
    stock: 90,
    categorySlugs: ['desktops', 'cpus', 'video-cards-gpus'],
    images: placeholderImg('Desktop Trident AS'),
  },
  {
    name: 'Beelink SER5 Mini PC Ryzen 7',
    slug: 'beelink-ser5-ryzen-7',
    description: 'Powerful AMD mini PC.',
    price: 359.0,
    stock: 160,
    categorySlugs: ['desktops', 'cpus'],
    images: placeholderImg('Desktop Beelink SER5'),
  },
  {
    name: 'Origin PC Neuron Custom Gaming Desktop',
    slug: 'origin-pc-neuron-custom',
    description: 'Build-to-order high-end gaming PC.',
    price: 2499.0,
    stock: 50,
    categorySlugs: [
      'desktops',
      'cpus',
      'video-cards-gpus',
      'motherboards',
      'memory-ram',
      'storage',
      'power-supplies-psus',
      'pc-cases',
      'pc-cooling',
    ],
    images: placeholderImg('Desktop Origin Neuron', 3),
  },

  // --- Cables & Adapters (10+) ---
  {
    name: 'Anker USB-C to USB-C Cable (10ft, 100W)',
    slug: 'anker-usbc-cable-10ft-100w',
    description: 'Long high-power USB-C cable.',
    price: 19.99,
    stock: 500,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Cable USB-C 10ft'),
  },
  {
    name: 'Amazon Basics HDMI Cable (6ft, 4K)',
    slug: 'amazon-hdmi-cable-6ft-4k',
    description: 'Standard HDMI cable.',
    price: 6.99,
    stock: 1000,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Cable HDMI 6ft'),
  },
  {
    name: 'Cable Matters DisplayPort 1.4 Cable (6ft)',
    slug: 'cablematters-dp14-cable-6ft',
    description: 'High-bandwidth DisplayPort cable.',
    price: 12.99,
    stock: 400,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Cable DP 1.4 6ft'),
  },
  {
    name: 'UGREEN USB-C Hub 7-in-1 Adapter',
    slug: 'ugreen-usbc-hub-7in1',
    description: 'Multiport USB-C adapter.',
    price: 39.99,
    stock: 300,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Hub USB-C 7in1', 2),
  },
  {
    name: 'StarTech USB 3.0 to SATA Adapter Cable',
    slug: 'startech-usb3-sata-adapter',
    description: 'Connect SATA drives via USB.',
    price: 14.99,
    stock: 250,
    categorySlugs: ['cables-adapters', 'storage'],
    images: placeholderImg('Adapter USB SATA'),
  },
  {
    name: 'Anker USB-C to Lightning Cable (6ft, MFi)',
    slug: 'anker-usbc-lightning-6ft',
    description: 'MFi certified iPhone charging cable.',
    price: 17.99,
    stock: 600,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Cable Lightning 6ft'),
  },
  {
    name: 'Monoprice Cat6 Ethernet Patch Cable (10ft)',
    slug: 'monoprice-cat6-cable-10ft',
    description: 'Standard network cable.',
    price: 5.99,
    stock: 800,
    categorySlugs: ['cables-adapters', 'networking'],
    images: placeholderImg('Cable Cat6 10ft'),
  },
  {
    name: 'Apple USB-C Digital AV Multiport Adapter',
    slug: 'apple-usbc-av-adapter',
    description: 'Apple HDMI/USB adapter.',
    price: 69.0,
    stock: 150,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Adapter Apple AV'),
  },
  {
    name: 'VENTION HDMI to VGA Adapter',
    slug: 'vention-hdmi-vga-adapter',
    description: 'Connect HDMI source to VGA display.',
    price: 9.99,
    stock: 200,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Adapter HDMI VGA'),
  },
  {
    name: 'JSAUX USB-C Right Angle Cable (3ft)',
    slug: 'jsaux-usbc-right-angle-3ft',
    description: 'Right-angle USB-C cable.',
    price: 10.99,
    stock: 350,
    categorySlugs: ['cables-adapters'],
    images: placeholderImg('Cable USB-C Angle'),
  },

  // --- Networking (10+) ---
  {
    name: 'ASUS RT-AX88U Pro WiFi 6 Router',
    slug: 'asus-rt-ax88u-pro-wifi6',
    description: 'High-performance WiFi 6 router.',
    price: 309.99,
    stock: 100,
    categorySlugs: ['networking'],
    images: placeholderImg('Router AX88U Pro', 2),
  },
  {
    name: 'TP-Link Archer AXE75 WiFi 6E Router',
    slug: 'tplink-archer-axe75-wifi6e',
    description: 'Affordable WiFi 6E router.',
    price: 199.99,
    stock: 150,
    categorySlugs: ['networking'],
    images: placeholderImg('Router AXE75 WiFi6E'),
  },
  {
    name: 'NETGEAR Nighthawk AX1800 WiFi 6 Mesh System (MK62)',
    slug: 'netgear-nighthawk-mk62-mesh',
    description: 'WiFi 6 mesh system (2-pack).',
    price: 229.99,
    stock: 120,
    categorySlugs: ['networking'],
    images: placeholderImg('Mesh MK62', 2),
  },
  {
    name: 'Ubiquiti UniFi Dream Machine Pro (UDM-Pro)',
    slug: 'ubiquiti-udm-pro',
    description: 'All-in-one UniFi network appliance.',
    price: 379.0,
    stock: 80,
    categorySlugs: ['networking'],
    images: placeholderImg('Router UDM Pro'),
  },
  {
    name: 'TP-Link Deco X55 WiFi 6 Mesh System (3-Pack)',
    slug: 'tplink-deco-x55-mesh-3pack',
    description: 'Popular WiFi 6 mesh system.',
    price: 209.99,
    stock: 180,
    categorySlugs: ['networking'],
    images: placeholderImg('Mesh Deco X55', 3),
  },
  {
    name: 'NETGEAR 5-Port Gigabit Ethernet Unmanaged Switch (GS305)',
    slug: 'netgear-gs305-switch',
    description: 'Simple 5-port gigabit switch.',
    price: 17.99,
    stock: 500,
    categorySlugs: ['networking'],
    images: placeholderImg('Switch GS305'),
  },
  {
    name: 'TP-Link TL-SG108 8-Port Gigabit Metal Switch',
    slug: 'tplink-tl-sg108-switch',
    description: 'Reliable 8-port metal switch.',
    price: 24.99,
    stock: 400,
    categorySlugs: ['networking'],
    images: placeholderImg('Switch TL-SG108'),
  },
  {
    name: 'Intel AX210 WiFi 6E + Bluetooth 5.3 PCIe Card',
    slug: 'intel-ax210-pcie-card',
    description: 'Internal WiFi/BT card for desktops.',
    price: 29.99,
    stock: 300,
    categorySlugs: ['networking', 'components'],
    images: placeholderImg('Card WiFi AX210'),
  },
  {
    name: 'TP-Link USB WiFi Adapter AC600 (Archer T2U Nano)',
    slug: 'tplink-ac600-usb-nano',
    description: 'Tiny USB WiFi adapter.',
    price: 14.99,
    stock: 600,
    categorySlugs: ['networking'],
    images: placeholderImg('Adapter USB AC600'),
  },
  {
    name: 'Motorola MB8611 DOCSIS 3.1 Cable Modem',
    slug: 'motorola-mb8611-modem',
    description: 'High-speed cable modem.',
    price: 179.99,
    stock: 110,
    categorySlugs: ['networking'],
    images: placeholderImg('Modem MB8611'),
  },

  // --- Software (10+) ---
  {
    name: 'Microsoft Windows 11 Pro (USB)',
    slug: 'microsoft-windows-11-pro-usb',
    description: 'Windows 11 Pro on USB drive.',
    price: 199.99,
    stock: 200,
    categorySlugs: ['software'],
    images: placeholderImg('OS Win11 Pro USB'),
  },
  {
    name: 'Microsoft Windows 11 Home (USB)',
    slug: 'microsoft-windows-11-home-usb',
    description: 'Windows 11 Home on USB drive.',
    price: 139.99,
    stock: 300,
    categorySlugs: ['software'],
    images: placeholderImg('OS Win11 Home USB'),
  },
  {
    name: 'Microsoft Office Home & Business 2021 (1 PC)',
    slug: 'microsoft-office-hb-2021',
    description: 'Office suite (Word, Excel, Outlook).',
    price: 249.99,
    stock: 150,
    categorySlugs: ['software'],
    images: placeholderImg('SW Office HB 2021'),
  },
  {
    name: 'Microsoft 365 Personal (1 Year Subscription)',
    slug: 'microsoft-365-personal-1yr',
    description: 'Subscription Office + Cloud Storage.',
    price: 69.99,
    stock: 500,
    categorySlugs: ['software'],
    images: placeholderImg('SW M365 Personal'),
  },
  {
    name: 'Adobe Photoshop Elements 2024',
    slug: 'adobe-photoshop-elements-2024',
    description: 'Consumer photo editing software.',
    price: 99.99,
    stock: 100,
    categorySlugs: ['software'],
    images: placeholderImg('SW Photoshop Elements'),
  },
  {
    name: 'Adobe Premiere Elements 2024',
    slug: 'adobe-premiere-elements-2024',
    description: 'Consumer video editing software.',
    price: 99.99,
    stock: 100,
    categorySlugs: ['software'],
    images: placeholderImg('SW Premiere Elements'),
  },
  {
    name: 'Norton 360 Deluxe Antivirus (5 Devices, 1 Year)',
    slug: 'norton-360-deluxe-1yr',
    description: 'Antivirus and security suite.',
    price: 49.99,
    stock: 400,
    categorySlugs: ['software'],
    images: placeholderImg('SW Norton 360'),
  },
  {
    name: 'Acronis True Image 2024 (Backup Software)',
    slug: 'acronis-true-image-2024',
    description: 'Disk imaging and backup solution.',
    price: 59.99,
    stock: 120,
    categorySlugs: ['software'],
    images: placeholderImg('SW Acronis True Image'),
  },
  {
    name: 'TurboTax Deluxe 2023 Federal + State',
    slug: 'turbotax-deluxe-2023',
    description: 'Tax preparation software.',
    price: 59.99,
    stock: 250,
    categorySlugs: ['software'],
    images: placeholderImg('SW TurboTax Deluxe'),
  },
  {
    name: 'VMware Workstation Pro 17',
    slug: 'vmware-workstation-pro-17',
    description: 'Virtual machine software.',
    price: 199.0,
    stock: 80,
    categorySlugs: ['software'],
    images: placeholderImg('SW VMware Workstation'),
  },

  // --- PC Cooling (10+) ---
  {
    name: 'Noctua NH-D15 Chromax.Black CPU Air Cooler',
    slug: 'noctua-nh-d15-chromax-black',
    description: 'Top-tier air cooler (black).',
    price: 119.95,
    stock: 150,
    categorySlugs: ['pc-cooling', 'cpus'],
    images: placeholderImg('Cooler NH-D15 Black', 2),
  },
  {
    name: 'Thermalright Phantom Spirit 120 SE ARGB CPU Cooler',
    slug: 'thermalright-ps120-se-argb',
    description: 'Best value high-performance air cooler.',
    price: 35.9,
    stock: 300,
    categorySlugs: ['pc-cooling', 'cpus'],
    images: placeholderImg('Cooler PS120 SE'),
  },
  {
    name: 'Corsair iCUE H150i Elite Capellix XT 360mm AIO',
    slug: 'corsair-h150i-elite-capellix-xt',
    description: 'Popular 360mm AIO liquid cooler.',
    price: 219.99,
    stock: 120,
    categorySlugs: ['pc-cooling', 'cpus'],
    images: placeholderImg('AIO H150i Elite XT', 2),
    options: [{ name: 'Color', values: ['Black', 'White'] }],
    variants: [
      { optionValues: ['Black'], price: 219.99, stock: 70 },
      { optionValues: ['White'], price: 229.99, stock: 50 },
    ],
  },
  {
    name: 'Arctic Liquid Freezer II 280 AIO Cooler',
    slug: 'arctic-liquid-freezer-ii-280',
    description: 'High-performance 280mm AIO.',
    price: 114.99,
    stock: 180,
    categorySlugs: ['pc-cooling', 'cpus'],
    images: placeholderImg('AIO Arctic LF II 280'),
  },
  {
    name: 'Noctua NF-A12x25 PWM Premium Quiet Fan',
    slug: 'noctua-nf-a12x25-pwm',
    description: 'Best all-around 120mm case fan.',
    price: 32.95,
    stock: 400,
    categorySlugs: ['pc-cooling'],
    images: placeholderImg('Fan NF-A12x25'),
  },
  {
    name: 'Arctic P12 PWM PST Value Pack (5 Fans)',
    slug: 'arctic-p12-pwm-pst-5pack',
    description: 'Best value 120mm fans.',
    price: 34.99,
    stock: 500,
    categorySlugs: ['pc-cooling'],
    images: placeholderImg('Fan P12 5-Pack'),
  },
  {
    name: 'Lian Li UNI FAN SL-Infinity 120 RGB (3 Pack + Controller)',
    slug: 'lianli-sl-inf-120-3pack',
    description: 'Infinity mirror RGB fans.',
    price: 99.99,
    stock: 200,
    categorySlugs: ['pc-cooling'],
    images: placeholderImg('Fan SL-INF 120', 3),
    options: [{ name: 'Color', values: ['Black', 'White'] }],
    variants: [
      { optionValues: ['Black'], price: 99.99, stock: 120 },
      { optionValues: ['White'], price: 99.99, stock: 80 },
    ],
  },
  {
    name: 'be quiet! Silent Wings 4 Pro 140mm PWM Fan',
    slug: 'bequiet-silent-wings-4-pro-140',
    description: 'Ultra-quiet high-performance 140mm fan.',
    price: 31.9,
    stock: 160,
    categorySlugs: ['pc-cooling'],
    images: placeholderImg('Fan SW4 Pro 140'),
  },
  {
    name: 'Thermal Grizzly Kryonaut Thermal Paste (1g)',
    slug: 'thermal-grizzly-kryonaut-1g',
    description: 'High-performance thermal paste.',
    price: 8.99,
    stock: 600,
    categorySlugs: ['pc-cooling', 'cpus', 'video-cards-gpus'],
    images: placeholderImg('Paste Kryonaut'),
  },
  {
    name: 'Cooler Master MasterGel Pro V2 Thermal Paste',
    slug: 'cm-mastergel-pro-v2',
    description: 'Good value thermal paste.',
    price: 6.99,
    stock: 500,
    categorySlugs: ['pc-cooling', 'cpus', 'video-cards-gpus'],
    images: placeholderImg('Paste MasterGel Pro'),
  },
];
